algo_params:
  name: 'ppo_non_quantized'
  k_epochs: 7
  batch_size: 128
  min_batch_size: 4096
  episodes: 4000
  lam: 0.95
  gamma: 0.99
  actor_lr: 0.001
  critic_lr: 0.003
  std_min_clip:  0.001
  eps_clip: 0.3
  beta: 0.09
  max_steps: 5000
  max_reward: 100
  
network_params:
  conv_layers: [[4, 5, 5]]
  avg_pool: [2, 2]
  hid_layers: [256, 256]
  net_is_shared: false
  act_fn: 'relu'
  action_space: 'cont'
  init_logstd: 0.1

env_params:
  obs_scale_factor: 0.25
  positions: [[-0.5, 0.5], [8.5, 0.5], [8.5, -8.5]]
  angles: [0, 45, 90, 135, 180, 225, 270, 315]
  noise_std: 10
