<?xml version="1.0" ?>
<robot name="custom_turtle" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find rl_tb3)/urdf/tb3commprop.xacro"/>
  <xacro:include filename="$(find rl_tb3)/urdf/tb3.gazebo.xacro"/>
  <xacro:include filename="$(find realsense2_description)/urdf/_materials.urdf.xacro" />

  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="d455_cam_depth_to_infra1_offset" value="0.0"/>
  <xacro:property name="d455_cam_depth_to_infra2_offset" value="-0.095"/>
  <xacro:property name="d455_cam_depth_to_color_offset" value="-0.059"/>
  <xacro:property name="d455_cam_width" value="0.124"/>
  <xacro:property name="d455_cam_height" value="0.029"/>
  <xacro:property name="d455_cam_depth" value="0.026"/>
  <xacro:property name="d455_cam_mount_from_center_offset" value="0.0158"/>
  <!-- glass cover is 0.1 mm inwards from front aluminium plate -->
  <xacro:property name="d455_glass_to_front" value="0.1e-3"/>
  <!-- see datasheet Revision 009, Fig. 4-4 page 68 -->
  <xacro:property name="d455_zero_depth_to_glass" value="4.55e-3"/>
  <!-- convenience precomputation to avoid clutter-->
  <xacro:property name="d455_mesh_x_offset" value="${d455_cam_mount_from_center_offset-d455_glass_to_front-d455_zero_depth_to_glass}"/>

  <!-- The following offset is relative to the physical d455 camera peripherial
  camera tripod mount -->
  <xacro:property name="d455_cam_depth_px" value="${d455_cam_mount_from_center_offset}"/>
  <xacro:property name="d455_cam_depth_py" value="0.0475"/>
  <xacro:property name="d455_cam_depth_pz" value="${d455_cam_height/2}"/>


  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 0.010" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="-0.032 0 0.00" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/bases/burger_base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="-0.032 0 0.070" rpy="0 0 0"/>
      <geometry>
        <box size="0.140 0.140 0.143"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="8.2573504e-01"/>
      <inertia ixx="2.2124416e-03" ixy="-1.2294101e-05" ixz="3.4938785e-05"
               iyy="2.1193702e-03" iyz="-5.0120904e-06"
               izz="2.0064271e-03" />
    </inertial>
  </link>

  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left_link"/>
    <origin xyz="0.0 0.08 0.023" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/wheels/left_tire.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right_link"/>
    <origin xyz="0.0 -0.080 0.023" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/wheels/right_tire.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

  <joint name="caster_back_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_back_link"/>
    <origin xyz="-0.081 0 -0.004" rpy="-1.57 0 0"/>
  </joint>

  <link name="caster_back_link">
    <collision>
      <origin xyz="0 0.001 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.030 0.009 0.020"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.005" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="-0.032 0 0.068" rpy="0 0 0"/>
  </joint>

  <link name="imu_link"/>

  <joint name="camera_joint" type="fixed">
    <origin xyz="-0.045 0 0.171" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="camera_bottom_screw_frame" />
  </joint>

  <link name="camera_bottom_screw_frame"/>

  <joint name="camera_link_joint" type="fixed">
    <origin xyz="${d455_mesh_x_offset} ${d455_cam_depth_py} ${d455_cam_depth_pz}" rpy="0 0 0"/>
    <parent link="camera_bottom_screw_frame"/>
    <child link="camera_link" />
  </joint>

  <link name="camera_link">
    <visual>
      <!-- the mesh origin is at front plate in between the two infrared camera axes -->
      <!-- <origin xyz="${d455_zero_depth_to_glass-d455_cam_depth/2} ${-d455_cam_depth_py} 0" rpy="0 0 0"/> -->
      <origin xyz="${d455_zero_depth_to_glass + d455_glass_to_front} ${-d455_cam_depth_py} 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
      <geometry>
        <!-- <box size="${d455_cam_depth} ${d455_cam_width} ${d455_cam_height}"/> -->
        <mesh filename="package://realsense2_description/meshes/d455.stl" scale="0.001 0.001 0.001" />
      </geometry>
      <material name="aluminum"/>
    </visual>
    <collision>
      <origin xyz="${d455_zero_depth_to_glass-d455_cam_depth/2} ${-d455_cam_depth_py} 0" rpy="0 0 0"/>
      <geometry>
        <box size="${d455_cam_depth} ${d455_cam_width} ${d455_cam_height}"/>
      </geometry>
    </collision>
  </link>

  <joint name="camera_depth_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_depth_frame" />
  </joint>

  <link name="camera_depth_frame"/>

  <joint name="camera_depth_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
    <parent link="camera_depth_frame" />
    <child link="camera_depth_optical_frame" />
  </joint>
  <link name="camera_depth_optical_frame"/>

  <joint name="camera_color_joint" type="fixed">
    <origin xyz="0 ${d455_cam_depth_to_color_offset} 0" rpy="0 0 0" />
    <parent link="camera_link" />
    <child link="camera_color_frame" />
  </joint>
  <link name="camera_color_frame"/>

  <joint name="camera_color_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
    <parent link="camera_color_frame" />
    <child link="camera_color_optical_frame" />
  </joint>
  <link name="camera_color_optical_frame"/>

</robot>