act_fn: elu
action_space: cont
actor_lr: 3.0e-05
batch_size: 5
beta: 0.001
conv_layers:
- - 16
  - 5
  - 1
- - 32
  - 3
  - 1
critic_lr: 7.0e-05
eps_clip: 0.1
ext_coef: 5
hid_layer:
- 512
- 256
- 128
k_epochs: 4
max_pool:
- 2
- 2
max_steps: 10000
min_batch_size: 20
name: rnd_ppo_5
obs_scale_factor: 0.1
positions:
- - 1
  - -1
- - 1
  - -2
pre_steps: 200
pred_lr: 1.0e-05
rnd_hid_layer:
- 512
- 256
- 128
std_min_clip: 0.1
