PARENTFOLDER = '/home/user/fyp/src/rl_tb3'

PLOTFOLDER = f'{PARENTFOLDER}/plots'
MODELFOLDER = f'{PARENTFOLDER}/models'
CHECKPOINTFOLDER = f'{PARENTFOLDER}/checkpoints'
STATUSFILE= f'{PARENTFOLDER}/status.txt'
REWARDFOLDER = f'{PARENTFOLDER}/rewards'